#slf4j logger
logging.file.name=logs/roomescape.log
logging.logback.rollingpolicy.file-name-pattern=logs/roomescape-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB
#h2 db
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.data-locations=classpath:db/data.sql
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:database
