spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test
spring.h2.console.path=/h2-console
# 1. JdbcTemplate? ???? SQL? ??? (DEBUG ??)
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# 2. ???(?)? ?? ?? ????? ??? (TRACE ??)
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
