spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/springjdbc;
    hikari:
      username: sa
      password:
      driver-class-name: org.h2.Driver
