DROP TABLE customers IF EXISTS
CREATE TABLE customers(id SERIAL, first_name VARCHAR(255), last_name VARCHAR(255))
DROP TABLE reservations IF EXISTS
CREATE TABLE reservations(id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, date VARCHAR(255) NOT NULL, time VARCHAR(255) NOT NULL, PRIMARY KEY (id) )