DROP TABLE customers IF EXISTS
CREATE TABLE customers(id SERIAL, first_name VARCHAR(255), last_name VARCHAR(255))

DROP TABLE times IF EXISTS
CREATE TABLE times(id BIGINT NOT NULL AUTO_INCREMENT, time VARCHAR(255) NOT NULL, PRIMARY KEY(id))

DROP TABLE reservations IF EXISTS
CREATE TABLE reservations(id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(255) NOT NULL, date VARCHAR(255) NOT NULL, time_id BIGINT, PRIMARY KEY (id), FOREIGN KEY (time_id) REFERENCES times(id))
